### ISSUE TITLE
Could not create temporary data tables due to foreign key constraint

### ISSUE THREAD

**Issue by slice** [mserajnik/hydrusrv#1]
There seems to be something about my server database that hydrusrv isn't taking so well:

```
hydrusrv_1  | $ node ./storage/migrate.js
hydrusrv_1  | Done in 0.72s.
hydrusrv_1  | Could not create temporary data tables. Error:
hydrusrv_1  | SqliteError: FOREIGN KEY constraint failed
```

Not sure how this came about, I simply transferred all of my tags to my server using the advanced feature from "review services".

**Comment by mserajnik** [comment]
Thanks for the report.

> I simply transferred all of my tags to my server using the advanced feature from "review services".

This is exactly how I do it as well, so this should be fine.

I've had quite a few issues in the past when trying to insert mappings for file IDs that don't exist (and with don't exist I mean hydrusrv didn't fetch a file with such an ID from hydrus server). To be honest, I still haven't figured out how and when exactly something like that can happen (to me it looks like the relevant files and mappings tables aren't always 100% in sync in hydrus server itself, which can cause issues when I'm fetching the data), but I thought I had at least managed to prevent the application from crashing if this occurs by explicitly only inserting mappings for file IDs that have been fetched.

The fact that this error still occurs should mean that the mappings and tag IDs can also be out of sync. I've just released a new version that should patch this, could you try updating and letting me know if that works for you?

**Comment by slice** [comment]
The patch didn't seem to work.

**Comment by slice** [comment]
Nevermind. I forgot to copy `app.db.template` as my new `data/app.db`. Doing that and restarting the app worked! Seems like I needed a fresh db.

**Comment by mserajnik** [comment]
And in case this wasn‘t clear enough from the hydrusrv-docker readme: you do need to rebuild the images every time you update it (as described in the previous comment). In addition, you need to rebuild them with the `--no-cache` flag if you want to update hydrus server to a new version (I just download the latest release via `wget` which is not re-evaluated by Docker when build caching is enabled).

I realize that‘s a bit of a hassle, but mounting the hydrusrv code in a volume instead didn‘t feel too good when I tried it.

I’ve automated the update process on my private server with a little script; it checks for new releases and then shuts down, rebuilds and restarts the containers on its own.

Needs some more refinement (e.g., it currently doesn‘t version check, so if I made a new major release that breaks something it would still update as usual), but once that‘s done I‘ll probably add that script to hydrusrv-docker to make this whole update process easier in actual production environments.
