### ISSUE TITLE
Increase request performance further

### ISSUE THREAD

**Issue by mserajnik** [mserajnik/hydrusrv#12]
With the recent release of `4.0.0`, hydrusrv can now use multiple workers, increasing the amount of requests it can handle in a given timeframe.

However, some queries (especially more complicated file listing queries on larger DBs) can still take a considerable amount of time (upwards of 100ms). Due to the synchronous nature of better-sqlite3 each request will block a worker for the amount of time the query takes to complete.

E.g., a set of 10 or more complex queries in a row might take 100ms each, effectively meaning that a single worker could only handle 9-10 requests per second. Even with multiple workers that's not a great amount if we take into account that hydrusrv _might_ be used for installations with many users. To keep scalability reasonable, increasing the amount of requests every single worker can handle in a given timeframe should be a priority.

better-sqlite3 is already the fastest SQLite library for Node.js. Using a different one with an asynchronous API could eliminate the worker blocking, but individual request performance would suffer, so that's not an option (for now; better alternatives might become available in the future).

Instead, the focus should be on the following points:

- The queries themselves can probably be improved quite a bit further because the developer of better-sqlite3 [writes](https://github.com/JoshuaWise/better-sqlite3#when-is-this-library-not-appropriate):
> With proper indexing, we've been able to achieve upward of 2000 queries per second with 5-way-joins in a 60 GB database, where each query was handling 5–50 kilobytes of real data.
- Non-query-related code that's obviously going to delay a response has to be reviewed as well; e.g., how efficient is [this hex conversion](https://github.com/mserajnik/hydrusrv/blob/4.1.0/server/models/files.js#L240-L247) that needs to run for every file in a result set and wouldn't it be better to convert the blob with SQLites `HEX()` function when copying over the data with hydrusrv-sync to decrease response time? 
- Comparisons for queries through hydrusrv and the [SQLite CLI](https://www.sqlite.org/cli.html) can be made to identify potential application bottlenecks that are currently not obvious (e.g., a query might seem slow when in reality it's fast and it's some other code in hydrusrv that's causing the delay)

Decreasing the time synchronous tasks take will improve both the requests per second _and_ the time a single request takes further, that's a win-win. But improving the performance of asynchronous/non-blocking code might be worthwile as well to _just_ increase individual request performance.

__Edit 1:__ Using additional indexes and covering indexes might be worthwhile to check out as described [here](https://medium.com/@JasonWyatt/squeezing-performance-from-sqlite-indexes-indexes-c4e175f3c346). E.g., having indexes (and probably a covering index as well?) on the two foreign keys on the `mappings` table and joining when querying files by tags _might_ be faster than the current [subquery solution](https://github.com/mserajnik/hydrusrv/blob/4.1.0/server/models/files.js#L144-L159). 

Until now I wasn't aware that creating a foreign key doesn't automatically create an index in SQLite:

> So, in most real systems, an index should be created on the child key columns of each foreign key constraint.

See [here](https://www.sqlite.org/foreignkeys.html#fk_indexes).

**Comment by mserajnik** [comment]
I've done some testing on Robert's DB (since it's the largest one available to me right now) and couldn't get any query variant to work faster than the current subquery solution when querying files by tags, even with indexes on the foreign keys of `mappings`.

__But__, while adding the indexes doubled the size of the content DB (from around 160MB to 320MB) due to the 7m mappings, the subquery performance went up _significantly_. Using the following query (that's the same as is used in hydrusrv), it reduced the time from `2393ms` to just `42ms`:

```sql
SELECT
  files.id,
  files.mime,
  files.size,
  files.width,
  files.height,
  files.hash
FROM
  files
WHERE
  files.tags_id IN (
    SELECT file_tags_id FROM mappings WHERE tag_id IN (
      SELECT id FROM tags WHERE name IN ('series:touhou', 'character:cirno')
    )
    GROUP BY file_tags_id
    HAVING COUNT(*) = 2
  )
ORDER BY
  files.id
LIMIT
  42
OFFSET
  0
```

I didn't test any more expensive queries (with sorting and exclude tags) but it's safe to say those will still be significantly faster as well.

Also, I've done some small improvements to a few other queries that can be seen [here](https://github.com/mserajnik/hydrusrv/commit/1fdb30a18f7738ff3e84c582540fe10854bf3a43).

Turns out that the query to fetch all the tags for a file was abysmally slow because the join happened from the wrong direction. On Robert's DB, this took around 15 seconds (!) before and is now down to less than 1ms. This query also benefits quite heavily from the indexes on `mappings` as it would take 1769ms without (and I didn't even test how slow the previous one that took 15 seconds would've been without the indexes).

The two queries to get the file and tag count were also a lot slower (around 40ms) when using `COUNT()` on a specific field instead of just using `COUNT(*)` (around 10ms). That's not a lot of saving, but every little bit counts in the grand scheme I guess.

All those numbers are raw query times (via the SQLite CLI), so the response times of the hydrusrv API will be slightly higher, of course.

All in all, I think those are some good improvements. I still want to try converting the blob directly in the query (as mentioned above) because I'm guessing that will save a few ms on file queries (at least when running a higher `FILES_PER_PAGE` setting).

New releases of hydrusrv and hydrusrv-sync probably tomorrow.

I'm planning to rename the tables in the content DB in the next release (dropping the `hydrusrv_` prefix) to match the authentication DB, somehow forgot that in the `4.0.0` release. This means you might want to recreate the content DB ones since the old tables won't be cleaned up automatically. Sorry, but I'd rather do this now than later.

**Comment by mserajnik** [comment]
My assumption that using `hash.toString('hex')` is quite expensive was right. For a set of 42 files (the default in hydrusrv) it takes around 20-30ms to compute the hex value.

Therefore, I'm getting rid of these computations in the next release and instead use SQLite's `HEX()` together with `LOWER()` to pre-comoute the hex values when syncing. This will increase database size a bit, but not too a huge degree (much less than adding the indexes did).

**Comment by mserajnik** [comment]
All done. I'll leave this open for now in case I (or someone else) come up with additional ideas.

**Comment by FredericaBernkastel** [comment]
You nailed it!
For me, file query timings dropped from `45/90/210ms` to `8/9/31ms`.

**Comment by FredericaBernkastel** [comment]
The ["union not in"](/mserajnik/hydrusrv/blob/290e5fb72cd05f73b454002906b8a1784ce87f21/server/models/files.js#L153-L155) slows down the query atleast 2 times. What about storing count of mappings for each file?

Plus, later we can easilly add `"system:number of tags"` query.

**Comment by mserajnik** [comment]
You mean just a total count of tags each file has, right? So we could check `WHERE tags_count = 0` instead of the union?

Sure, why not, that's a good idea, doesn't increase the database size by much as well.

Not sure what the fastest way to do that would be though. Do you wanna give it a try yourself?

**Comment by FredericaBernkastel** [comment]
Yes, i'll try.
Also, instead of separating hydrusrv and hydrusrv-sync into different repositories, can you add submodule? Because i will have to open 2 PRs instead 1 every time.

**Comment by mserajnik** [comment]
Nah, I want to keep them separate. Having hydrusrv as a submodule of hydrusrv-docker was a pain in the past and I'm glad that's gone now, much easier to maintain.

Sorry, we'll have to live with it when it comes to changes that affect both repos. :P

**Comment by FredericaBernkastel** [comment]
Search is working fine, problem with "getOfFile" query.

**Comment by mserajnik** [comment]
Whoops, I'm joining on the wrong query now: https://github.com/mserajnik/hydrusrv/blob/1fdb30a18f7738ff3e84c582540fe10854bf3a43/server/models/tags.js#L53

Sorry, I missed that when I reversed the join to make it faster. Will be fixed later today when I'm home from work (or in case I find the time at lunch break).

**Comment by mserajnik** [comment]
Fixed: https://github.com/mserajnik/hydrusrv/commit/8c40f10d379ef327eb3bc05813c6075571b652f0

New hydrusrv-docker release once the [automated Docker Hub build](https://hub.docker.com/r/mserajnik/hydrusrv/builds/) has finished.
