### ISSUE TITLE
Add wildcard tag searches

### ISSUE THREAD

**Issue by mserajnik** [mserajnik/hydrusrv#17]
# Wildcard tag searches

## Outline

It should be possible to search for files via "wildcarded" tags, e.g. `creator:*` or `*hair`.

`*` is the wildcard marker. An unlimited number of wildcarded tags can be provided. A maximum of two markers can be used for each tag and they must always be at the beginning and/or the end of the string. Additionally provided ones will be stripped if at the beginning or end (e.g., `creator:** -> creator:*`) and taken literally if in the middle of the string (e.g., `blue*hair` will search for exactly that tag, without considering `*` to be a wildcard marker).

Also, searches for the marker alone (`*`) should just return all files that have _any_ tags by a simple `NOT NULL` comparison on `files.tags_id`. Extra care must be taken to not overlook this special case, as it will negatively impact performance _a lot_ if handled like a regular wildcard tag.

Wildcard tag searches should work in combination with the already existing tags and exclude tags search and also the _system constraints_ mentioned in #16.

## API

The `tags[]` query parameter can be reused, just like with exclude tags:

```tags[]=partial%2A```

or

```tags[]=%2Apartial%2A```

`%2A` is `*` in encoded form. In reality, `[` and `]` need to be encoded as well, but I left that out to make it easier to read here.

Prefixing the wildcard marker with `\` (e.g., `creator:\*`) will search for the character literally (so, `creator:*`, using the same example) instead of starting a wildcard search. As with excluded tags, this prefix is only necessary if the user wants to escape the `*` at the beginning or end of the string, not when it's somewhere in the middle (in which case the `*` will be taken literally and not considered a marker automatically, as mentioned in the outline).

## Frontend

In hydrusrvue, this is best handled just like exclude tags (but maybe stop the autocomplete showing suggestions once the wildcard marker is entered).

## Timeframe

Work on this will be started after finishing #16, so likely at the end of January/the beginning of February. I plan to finish this by the end of February.

**Comment by FredericaBernkastel** [comment]
> Also, searches the marker alone (*) should just return all files that have tags by a simple null comparison on the mappings table.

Did you mean "`from hydrusrv_files where tags_id is not null`"?

**Comment by FredericaBernkastel** [comment]
Or just automatically convert it to **`system:number of tags>0`**. This will clarify alot for end users.

**Comment by mserajnik** [comment]
Maybe in the frontend, not sure about it yet though. In any case, I'll explain it in the _Help_ view.

**Comment by mserajnik** [comment]
The first WIP version is done:

- [`hydrusrv/feature/wildcard-tags`](https://github.com/mserajnik/hydrusrv/tree/feature/wildcard-tags)
- [`hydrusrvue/feature/wildcard-tags`](https://github.com/mserajnik/hydrusrvue/tree/feature/wildcard-tags) (the current version of hydrusrvue doesn't break when using `*`, but this makes it behave nicer)

I will push updates to those when I make changes/fixes in the coming days.

The frontend shortcut of using `*` and `-*` for `tags>0` and `tags=0` constraints is not yet in (in fact, I don't allow submitting `*` and `-*` for now, along with some other stuff like `-` that made no sense before) but will come soon.

Other than that, it seems to work pretty well. Even excluding whole namespaces (e.g., `-creator:*`) works. I didn't do a lot of tests yet though, so there might still be (edge) cases where something breaks.

**Comment by mserajnik** [comment]
Done:

- [`hydrusrv@8.0.0`](https://github.com/mserajnik/hydrusrv/commit/970efcd35f9fd03c9ed1292881261ce3c1991a8d)
- [`hydrusrvue@5.0.0`](https://github.com/mserajnik/hydrusrvue/commit/9013de0ebf1a2da5803030413b193639bf701e59)

New hydrusrv-docker release as soon as Docker Hub finishes building the images.

Aside from a few frontend bugs that are now fixed, nothing else came up when testing over the last few days.

The `*` and `-*` shortcuts in hydrusrvue to set `tags>0` and `tags=0` respectively are also in (forgot to mention them in the help, but I want to overhaul it in the near future anyway – not too happy with some parts of it when it comes to wording/ease of understanding).
